" Setup:
" After copying this file to your home directory, run the bin/setup-vim
" script to install the needed plugins.

" *** Vundle Config ***
" :PluginInstall ~ to install all listed Plugins
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" --- Open Plugins ---
" Plugin Manager
Plugin 'gmarik/Vundle.vim'
" Color Scheme
Plugin 'jnurmine/Zenburn'
" Zen Mode :Goyo
Plugin 'junegunn/goyo.vim'
" Python
Plugin 'vim-scripts/indentpython.vim'
Bundle 'Valloric/YouCompleteMe'
Plugin 'vim-syntastic/syntastic'
Plugin 'nvie/vim-flake8'
" --- Close Plugins ---
call vundle#end()

" Plugin Settings
let g:syntastic_python_checkers = ['python']
let g:syntastic_python_python_exec = 'python3'
let g:ycm_autoclose_preview_window_after_completion=1
let g:goyo_width = '60%'
let g:goyo_height = '100%'
let g:goyo_linenr = 1
let python_highlight_all=1
colorscheme zenburn


" *** Global Options ***
filetype plugin indent on
syntax on
set tabstop=2
set number
set splitbelow
set splitright
set encoding=utf-8
set backspace=indent,eol,start " Allow insert Backspace


" Navigate Splits
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Goyo Quit
function! s:goyo_enter()
	let b:quitting = 0
	let b:quitting_bang = 0
	autocmd QuitPre <buffer> let b:quitting = 1
	cabbrev <buffer> q! let b:quitting_bang = 1 <bar> q!
endfunction

function! s:goyo_leave()
	" Quit Vim if this is the only remaining buffer
  if b:quitting && len(filter(range(1, bufnr('$')), 'buflisted(v:val)')) == 1
    if b:quitting_bang
			qa!
		else
			qa
		endif
	endif
endfunction

autocmd! User GoyoEnter call <SID>goyo_enter()
autocmd! User GoyoLeave call <SID>goyo_leave()

