source ~/.prompt.zsh -h:green -d:blue
alias ls="ls --color=auto"
alias sandbox="source sandbox"
alias qd="source qd.sh"
alias tm="tmux new -s '?' || tmux"
TREMOTE="-f ~/.tmux.remote.conf"
alias tmr="tmux $TREMOTE new -s '?' || tmux $TREMOTE"
export PATH="$PATH$(cat ~/.macbin/.path)"
export PATH="$PATH:${HOME}/.local/bin"
