source ~/.prompt.zsh 'green' 'cyan'
alias ls="ls --color=auto"
alias sandbox="source sandbox"
alias qd="source qd.sh"
alias tm="tmux new -s '?' || tmux"
export PATH="$PATH$(cat ~/.macbin/.path)"
export PATH="$PATH:${HOME}/.local/bin"
