source ~/.prompt.zsh -h:blue -d:cyan
export CLICOLOR=1
export PATH="/usr/local/sbin:$PATH"


setup() {
	local callback=$1
	shift 1
	for cmd in $@
	do
		eval "$cmd() { $callback; $cmd "'$@'"; }"
	done
}


# Node
nvm_cmds=(nvm node npm npx firebase uvcc tsserver vim)
lazynvm() {
	unset -f $nvm_cmds
	export NVM_DIR="$HOME/.nvm"
	. "$(brew --prefix nvm)/nvm.sh"
}
setup lazynvm $nvm_cmds


# Java
jenv_cmds=(jenv java ghidraRun)
lazyjenv() {
	unset -f $jenv_cmds
	export JAVA_HOME=$(/usr/libexec/java_home)
	export PATH="$HOME/.jenv/bin:$PATH"
	eval "$(jenv init -)"
}
setup lazyjenv $jenv_cmds


# Ruby
rbenv_cmds=(rbenv ruby jekyll bundle)
lazyrbenv() {
	unset -f $rbenv_cmds
	export PATH="$HOME/.rbenv/bin:$PATH"
	old_pwd="$PWD"
	cd $HOME/.gem/ruby/
	for d in */ ; do
		b="bin"
		export PATH="$HOME/.gem/ruby/$d$b:$PATH"
	done
	cd $old_pwd
	eval "$(rbenv init -)"
}
setup lazyrbenv $rbenv_cmds

# Brew Completions
if type brew &>/dev/null; then
	FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
	autoload -Uz compinit
	compinit
fi

