#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/run.sh &
nm-applet &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           8

bspc config normal_border_color  '#3d3d3d'
bspc config active_boarder_color '#3d3d3d'
bspc config focused_border_color '#adadad'

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
